#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ALLOW_MISSING="${CHIO_HITRUST_ALLOW_MISSING:-0}"
DATE=""

usage() {
  cat <<'EOF_USAGE'
usage: build-evidence-pack.sh [--allow-missing] [DATE]

Build the HITRUST evidence bundle for DATE, defaulting to today in UTC.
Missing required repository evidence fails the build unless --allow-missing
or CHIO_HITRUST_ALLOW_MISSING=1 is set explicitly.
EOF_USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --allow-missing)
      ALLOW_MISSING="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [[ -n "$DATE" ]]; then
        echo "unexpected extra argument: $1" >&2
        usage >&2
        exit 2
      fi
      DATE="$1"
      shift
      ;;
  esac
done

DATE="${DATE:-$(date -u +%Y-%m-%d)}"
OUT="$ROOT/compliance/hitrust/evidence-bundles/$DATE"

allow_missing() {
  case "${ALLOW_MISSING}" in
    1|true|TRUE|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

copy_if_present() {
  local src="$1"
  local dst="$2"
  if [[ -e "$ROOT/$src" ]]; then
    mkdir -p "$(dirname "$OUT/$dst")"
    cp -R "$ROOT/$src" "$OUT/$dst"
  else
    printf 'missing,%s\n' "$src" >> "$OUT/MISSING.csv"
  fi
}

rm -rf "$OUT"
mkdir -p "$OUT"
: > "$OUT/MISSING.csv"

copy_if_present "spec/audit-log/export-schema.v1.json" "M01/audit-log/export-schema.v1.json"
copy_if_present ".planning/trajectory-3/audits/M01-healthcare-pilot.md" "M01/audit/M01-healthcare-pilot.md"
copy_if_present ".planning/trajectory-3/audits/M03-ci-restoration.md" "M03/audit/M03-ci-restoration.md"
copy_if_present ".github/workflows" "M03/workflows"
copy_if_present "docs/security/threat-coverage.md" "M05/threat-coverage.md"
copy_if_present "spec/security/chio-threat-model.v1.json" "M05/chio-threat-model.v1.json"
copy_if_present "supply-chain" "M06/supply-chain"
copy_if_present "formal" "M06/formal"
copy_if_present ".planning/trajectory-3/audits/M08-vendor-evidence.md" "M08/audit/M08-vendor-evidence.md"
copy_if_present "releases/audit-reports" "M08/audit-reports"
copy_if_present "compliance/hitrust/control-mapping.csv" "M09/control-mapping.csv"
copy_if_present "compliance/hitrust/gap-report/gap-report.md" "M09/gap-report.md"
copy_if_present "compliance/hitrust/policies" "M09/policies"
copy_if_present "compliance/hitrust/narratives" "M09/narratives"
copy_if_present "compliance/hitrust/ir-runbook.md" "M09/ir-runbook.md"
copy_if_present "compliance/hitrust/evidence-bundles/encryption-at-rest.md" "M09/encryption-at-rest.md"

(
  cd "$OUT"
  find . -type f ! -name SHA256SUMS ! -name README.md -print0 \
    | sort -z \
    | xargs -0 shasum -a 256
) > "$OUT/SHA256SUMS"

cat > "$OUT/README.md" <<EOF_README
# Chio HITRUST Evidence Bundle

Bundle date: $DATE
Scope: Chio v3.18 healthcare design-partner deployment

This bundle is generated by compliance/hitrust/build-evidence-pack.sh.
It gathers repository evidence only. Private BAA, HR, cloud-provider,
and tenant-sample artifacts must be uploaded through the assessor
evidence channel and referenced by hash.

Missing source list: MISSING.csv
Hash manifest: SHA256SUMS
EOF_README

if [[ -s "$OUT/MISSING.csv" ]]; then
  if allow_missing; then
    echo "warning: missing required HITRUST evidence; allow-missing mode enabled" >&2
  else
    echo "missing required HITRUST evidence; rerun with --allow-missing only for explicit incomplete-pack drills" >&2
    sed 's/^/  /' "$OUT/MISSING.csv" >&2
    exit 1
  fi
fi

echo "$OUT"
