[package]
name = "ttfrh-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "ttfrh-bench"
path = "src/main.rs"

[dependencies]
thiserror = { workspace = true }

[lints]
workspace = true
