//! Directory-owner utility for the two-machine deployment profile.
//! Node identities are generated by their owners; only public enrollment records enter here.
use anyhow::{Context, Result};
use chio_agent_os_shared::{events::now_ms, json, Value};
use chio_personal_network::directory::{self, Enrollment};
fn main() -> Result<()> {
    let file = std::env::args()
        .nth(1)
        .context("Provide an enrollment request file")?;
    let input: Value = serde_json::from_slice(&std::fs::read(file)?)?;
    let owner = directory::key(std::path::Path::new(
        input["owner_key_file"]
            .as_str()
            .context("Select the retained directory owner key file")?,
    ))?;
    let entries: Vec<Enrollment> = serde_json::from_value(input["nodes"].clone())?;
    let ttl = input["validity_seconds"].as_u64().unwrap_or(300);
    anyhow::ensure!(
        ttl > 0 && ttl <= 3600,
        "Directory lifetime must be 1 to 3600 seconds"
    );
    let mut bundles = Vec::new();
    for node in &entries {
        bundles.push(directory::bundle(
            &owner,
            &node.entry.kernel_id,
            entries.iter().map(|n| n.entry.clone()).collect(),
            1,
            None,
            now_ms() + ttl * 1000,
        )?);
    }
    println!(
        "{}",
        json!({"issuer":owner.public_key(),"directories":bundles})
    );
    Ok(())
}
