// Generated by scripts/build-workshop-local.mjs. Do not edit.
pub const BUILD_ID: &str = "703a75b3486c76fc1ba87298f5107ecb425074c9c2cb75e401ba5e348dd02431";
pub const HTML: &str = include_str!("../../ui/workshop/index.html");
pub fn asset(name: &str) -> Option<(&'static str, &'static [u8])> {
    match name {
        "0f48ea6abb2084537854-CormorantGaramond-Italic-wght-.ttf" => Some(("font/ttf", include_bytes!("../../ui/workshop/0f48ea6abb2084537854-CormorantGaramond-Italic-wght-.ttf"))),
        "b20b7d9626dd956b2c5e-CormorantGaramond-wght-.ttf" => Some(("font/ttf", include_bytes!("../../ui/workshop/b20b7d9626dd956b2c5e-CormorantGaramond-wght-.ttf"))),
        "b81b73dcb64df3c230ca-InterTight-wght-.ttf" => Some(("font/ttf", include_bytes!("../../ui/workshop/b81b73dcb64df3c230ca-InterTight-wght-.ttf"))),
        "48715a42ec242c21e9f0-JetBrainsMono-wght-.ttf" => Some(("font/ttf", include_bytes!("../../ui/workshop/48715a42ec242c21e9f0-JetBrainsMono-wght-.ttf"))),
        "fa24121fd5442aa237c0-workshop.js" => Some(("text/javascript; charset=utf-8", include_bytes!("../../ui/workshop/fa24121fd5442aa237c0-workshop.js"))),
        "24c6fb392a1a69243dd1-workshop.css" => Some(("text/css; charset=utf-8", include_bytes!("../../ui/workshop/24c6fb392a1a69243dd1-workshop.css"))),
        _ => None,
    }
}
